# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 19:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_auto_20170204_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='key_words',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 4, 19, 18, 34, 234358, tzinfo=utc), verbose_name='date published'),
        ),
    ]
