# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0007_auto_20170205_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
