# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0009_auto_20170206_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
