# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0010_picture_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='image_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='image_path',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='users',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='key_words',
        ),
    ]
