# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0005_user_balance'),
        ('picture', '0011_auto_20170207_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsys.User')),
            ],
        ),
    ]
