# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0012_testcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcart',
            name='pict',
        ),
        migrations.RemoveField(
            model_name='testcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='TestCart',
        ),
    ]
