# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0013_auto_20170207_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='sale_cout',
            field=models.IntegerField(default=0),
        ),
    ]
