# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0014_picture_sale_cout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='sale_cout',
            new_name='sale_count',
        ),
    ]
