# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0013_auto_20170207_1718'),
        ('cartsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='picture',
        ),
        migrations.AddField(
            model_name='cart',
            name='picture',
            field=models.ManyToManyField(to='picture.Picture'),
        ),
    ]
