# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0013_auto_20170207_1718'),
        ('authsys', '0005_user_balance'),
        ('cartsys', '0002_auto_20170207_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('picture', models.ManyToManyField(to='picture.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authsys.User')),
            ],
        ),
    ]
