# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartsys', '0006_auto_20170211_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='picture',
            field=models.ManyToManyField(blank=True, to='picture.Picture'),
        ),
    ]
